# -*- coding: utf-8 -*-
#######################################################
# This script saves result data                       #
# It expects the format of unladen swallow's perf.py  #
#######################################################

"""
Upload a json file generated by runner.py.

Revision, name and host are required.

Example usage:

  $ ./saveresults.py result.json -r '45757:fabe4fc0dc08' -n pypy-c-jit \
    -H benchmarker

  OR

  $ ./saveresults.py result.json -r '45757:fabe4fc0dc08' -n pypy-c-jit-64 \
    -H benchmarker
"""
from __future__ import division, print_function

from datetime import datetime
import optparse
import sys
import time
try:
    import urllib2
    from urllib import urlencode
except ImportError:
    import urllib.request as urllib2
    from urllib.parse import urlencode
import json
import pprint

SPEEDURL = 'http://127.0.0.1:8000/'
# SPEEDURL = 'https://speed.pypy.org/'

def save(project, revision, results, executable, host, url, testing=False,
         changed=True, branch='default'):
    testparams = []
    #Parse data
    data = {}
    error = 0

    print("saveresults::save sending from %s to %s" %(host, url))
    for b in results:
        bench_name = b[0]
        res_type = b[1]
        results = b[2]
        value = 0
        if res_type == "SimpleComparisonResult":
            if changed:
                value = results['changed_time']
            else:
                value = results['base_time']
        elif res_type == "ComparisonResult":
            if changed:
                value = results['avg_changed']
            else:
                value = results['avg_base']
        elif res_type == "RawResult":
            if changed:
                value = results["changed_times"]
            else:
                value = results["base_times"]
            if value:
                assert len(value) == 1
                value = value[0]
        else:
            print("ERROR: result type unknown " + b[1])
            return 1
        data = [{
            'commitid': revision,
            'project': project,
            'executable': executable,
            'benchmark': bench_name,
            'environment': host,
            'result_value': value,
            'branch': branch,
        }]
        if not value:
            print("Ignoring skipped result", data)
            continue
        if res_type == "ComparisonResult":
            if changed:
                data[0]['std_dev'] = results['std_changed']
            else:
                data[0]['std_dev'] = results['std_base']
        if testing:
            testparams.append(data)
        else:
            error |= send(data, url)

    if error:
        raise IOError("Saving failed.  See messages above.")
    if testing:
        return testparams
    else:
        return 0


def send(data, url):
    #save results
    params = urlencode({'json': json.dumps(data)}).encode("utf-8")
    f = None
    response = "None"
    info = ("%s: Saving result for %s revision %s, benchmark %s" %
            (str(datetime.today()), data[0]['executable'],
             str(data[0]['commitid']), data[0]['benchmark']))
    print(info)
    try:
        retries = [1, 3, 6, 20]
        while True:
            try:
                print('result/add')
                f = urllib2.urlopen(url + 'result/add/json/', params)
                print('urlopen')
                response = f.read().decode()
                print('response')
                f.close()
                break
            except urllib2.URLError:
                if not retries:
                    raise
                d = retries.pop(0)
                print("retrying in %d seconds..." % d)
                time.sleep(d)
    except urllib2.URLError as e:
        if hasattr(e, 'reason'):
            response = '\n  We failed to save the data\n'
            response += '  Reason: ' + str(e.reason)
        elif hasattr(e, 'code'):
            response = '\n  The server couldn\'t fulfill the request'
        if hasattr(e, 'readlines'):
            response = "".join([response] + [s.decode() for s in e.readlines()])
        print(response)
        print('when sending')
        pprint.pprint(data)
        raise
        with open('error.html', 'w') as error_file:
            error_file.write(response)
        print("Server (%s) response written to error.html" % (url,))
        print('  Error code: %s\n' % (e,))
        return 1
    print("saved correctly!", end='\n\n')
    return 0

if __name__ == '__main__':
    usage = "Usage: %prog [options] <results.json>"
    parser = optparse.OptionParser(usage=usage)
    parser.add_option('-b', '--base', action='store_true',
                      help='take base values instead of modified')
    parser.add_option('--host', type=str, default=SPEEDURL,
                      help="codespeed instance, defaults to '%s'" % SPEEDURL)
    parser.add_option('--revision',
         help=('for cpython, revision number (100 for cpython 2.6.2, 101 for 2.7.2, '
               '110 for cpython3.7.6, 120 for cpython3.11, '
               'edit admin interface "Revisions" to add more)\n\n'
               'for pypy, use the hash from the json file'),
        )
    parser.add_option('--branch', help="branch name (main, py3.11)", default='main')
    options, args = parser.parse_args(sys.argv)
    if options.host[-1] != '/':
        raise ValueError("host must end with '/'")
    if not options.host.startswith("http"):
        raise ValueError("host must start with 'http'")
    if len(args) != 2:
        print(parser.usage)
        sys.exit(1)
    results = json.load(open(args[1]))['results']
    save('cpython', options, results, 'cpython', 'benchmarker',
         testing=False)
